### ISSUE TITLE
Mechanical to Simulation: Integration with end effector

### ISSUE THREAD

**Issue by jueunkwon** [wengmister/Apex-Putter#9]
- [x] End Effector Prototype Created (Thanks Kris)

- [x] Ensure Putter Fits In End Effector 

- [x] Can it mimic movement if lightly putt from User? 

- [ ] Test different Congiurations

 - [x] Put End Effector On Franka and Test Fit On Robotic Side

- [x] Move Franka with End Effecto

- [x] Test Franka with club and end effector (could use a broomstick or similar shape

 - [ ] “Stress Test”
 
 - [x] YOLO sometimes detects the golf club as 2 balls. Either duck tape or spray paint the club to resolve the issue.

**Comment by wengmister** [comment]
![image](https://github.com/user-attachments/assets/a5ef314f-6af0-4abb-a933-40699f630ec7)

https://github.com/user-attachments/assets/07c02a0b-da6f-42ff-8721-b5140e077d06

Made a coupling for connecting putting club to EE

**Comment by wengmister** [comment]
![image](https://github.com/user-attachments/assets/3b1529bd-82d8-44f6-8473-5cead2d8c986)

Club topside has a M8x1.25x10mm thread

**Comment by wengmister** [comment]
![Image](https://github.com/user-attachments/assets/77b21212-1683-4cc8-930f-ee00cca652f7)
New clocked putter. Highlighted face is normal to +z axis of fer_L8/fer_joint8

![Image](https://github.com/user-attachments/assets/acb78ac7-584a-4b1f-b71d-02bb8a8fc99e)
This is now just a flat 518.8mm offset to a good hitting position
